packages:
  - packages/*
  # examples
  - packages/mcp-use/examples/**/*
  - packages/create-mcp-use-app/src/templates/**/*
  # tests
  - test_app
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
